### ISSUE TITLE
name 'train_ds' is not defined

### ISSUE THREAD

**Issue by franjamonga** [NLPPower/Aerial-Unet#1]
Good afternoon, first of all congratulate you on your code. I'm trying to replicate it in spyder-python and when I get to the part:
history = model.fit(train_ds, 
                   steps_per_epoch=int(np.ceil(num_train_examples / float(batch_size))),
                   epochs=epochs,
                   validation_data=val_ds,
                   validation_steps=int(np.ceil(num_val_examples / float(batch_size))),
                   callbacks=[cp])

I get the following error: name 'train_ds' is not defined. 
I also don't know what val_ds and test_ds mean. 
When trying to load the pre-trained model to see how it predicts, it also won't let me tell me that jaccard_loss is not found.

Thank you for your attention, I look forward to your response.

**Comment by NLPPower** [comment]
Thanks
Just change chose variables:
train_ds ==> train_dataset
val_ds ==> validation_dataset
test_ds ==> test_dataset

for second issues change this part in the load function
'dice_coeff': dice_coeff ==> 'dice_coeff': dice_para
